services:
  xray:
    image: zzwsec/xray
    container_name: xray
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "30000:30000"
    # environment:
    #   SNI: example.com
    # volumes:
    #   - ./data:/xray/data
