services:
  xray:
    image: zzwsec/xray
    container_name: xray
    restart: unless-stopped
    network_mode: bridge
    # environment:
    #   SNI: example.com
    ports:
      - "30000:30000"
    volumes:
      - ./data:/xray/data
